SunHotel/Controllers/AdminController.cs
using AutoMapper;
using DataBase.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Repository.Repository;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ViewModels;

namespace SunHotel.Controllers
{

    [Authorize]
    public class AdminController : Controller
    {

        private readonly TiposHabitacionRepository _tiposHabitacionRepository;
        private readonly HabitacionRepository _HabitacionRepository;
        private readonly EdificiosRepository _EdificiosRepository;
        private readonly imghabitacionRepository _imghabitacionRepository;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly ReservaRepository _reservaRepository;
        private readonly PagoRepository _pagoRepository;


        private readonly IWebHostEnvironment hostEnvironment;

        private readonly IMapper _mapper;

        public AdminController(TiposHabitacionRepository tiposHabitacionRepository, IMapper mapper, HabitacionRepository HabitacionRepository,
         EdificiosRepository EdificiosRepository, IWebHostEnvironment hostEnvironment, imghabitacionRepository imghabitacionRepository,
         SignInManager<IdentityUser> signInManager, ReservaRepository reservaRepository, PagoRepository pagoRepository)
        {
            this.hostEnvironment = hostEnvironment;
            _tiposHabitacionRepository = tiposHabitacionRepository;
            _HabitacionRepository = HabitacionRepository;
            _EdificiosRepository = EdificiosRepository;
            _mapper = mapper;
            _imghabitacionRepository = imghabitacionRepository;
            _signInManager = signInManager;
            _reservaRepository = reservaRepository;
            _pagoRepository = pagoRepository;
        }


        [HttpGet]
        public async  Task<IActionResult> Index()
        {
            var vm = new DashboardVM();
            var tipoHabitaciones = await _tiposHabitacionRepository.GetAll();
            var Habitaciones = await _HabitacionRepository.GetAll();
            var Edificios = await _EdificiosRepository.GetAll();
            var reservas = await _reservaRepository.GetAll();
           var counres= reservas.Where(a => a.FechaPago == DateTime.Today).ToList().Count;
            vm.CantTipohabitaciones = tipoHabitaciones.Count;
            vm.Canthabitaciones = Habitaciones.Count;
            vm.Cantedificios = Edificios.Count;
            vm.reservas = counres;

            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> Habitaciones()
        {
            var selectipos = await _tiposHabitacionRepository.Listselectipos();
            var selectedificios = await _EdificiosRepository.GetAll();
            if(selectipos != null)
            {
                ViewBag.tipos = selectipos;

            }
            if (selectedificios != null)
            {
                ViewBag.edificios = selectedificios;

            }
            var vm = await _HabitacionRepository.listahabtiacionesAdmin();
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> AñadirHabitaciones(HabitacionVM vm)
        {
           await _HabitacionRepository.addcustom(vm);
            return RedirectToAction("Habitaciones");
        }
      

        [HttpGet]
        public async Task<IActionResult> TiposHabitaciones()
        {
            var vm = await _tiposHabitacionRepository.GetAll();
            var vms = new TipoHabitacioneVM();
            vms.List = vm;
            return View(vms);
        }
        [HttpPost]
        public async Task<IActionResult> TiposHabitaciones(TipoHabitacioneVM vm)
        {

            if (ModelState.IsValid)
            {
                string uniqueName = null;
                var add = _mapper.Map<TipoHabitaciones>(vm);
                var save = await _tiposHabitacionRepository.Add(add);

                if (vm.photo != null)
                {
                    foreach (var pic in vm.photo)
                    {

                        uniqueName = Guid.NewGuid().ToString() + "_" + pic.FileName;
                        var folderPath = Path.Combine(hostEnvironment.WebRootPath, "img/habitacion");
                        var filepath = Path.Combine(folderPath, uniqueName);

                        if (filepath != null)
                        {

                            pic.CopyTo(new FileStream(filepath, mode: FileMode.Create));
                        }

                        var img = new ImgHabitaciones();

                        img.IdTipoHabitacion = save.IdTipoHabitacion;
                        img.Path = uniqueName;

                        await _imghabitacionRepository.Add(img);


                    }
                }
            }
            return RedirectToAction("TiposHabitaciones");


        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AñadirTipo(TipoHabitacioneVM vm)
        {

            if (ModelState.IsValid)
            {
                string uniqueName = null;
                var add = _mapper.Map<TipoHabitaciones>(vm);
                var save = await _tiposHabitacionRepository.Add(add);

                if (vm.photo != null)
                {
                    foreach (var pic in vm.photo)
                    {

                        uniqueName = Guid.NewGuid().ToString() + "_" + pic.FileName;
                        var folderPath = Path.Combine(hostEnvironment.WebRootPath, "img/habitacion");
                        var filepath = Path.Combine(folderPath, uniqueName);

                        if (filepath != null)
                        {

                            pic.CopyTo(new FileStream(filepath, mode: FileMode.Create));
                        }

                        var img = new ImgHabitaciones();

                        img.IdTipoHabitacion = save.IdTipoHabitacion;
                        img.Path = uniqueName;

                        await _imghabitacionRepository.Add(img);


                    }
                }
            }
            return RedirectToAction("TiposHabitaciones");


        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Borrartipo(TipoHabitacioneVM vm)
        {
            if (vm.eliminar.Value != 0)
            {

                var imgs = await _imghabitacionRepository.GetAll();

                var imgtipo = imgs.Where(a => a.IdTipoHabitacion == vm.eliminar.Value).ToList();

                foreach (var i in imgtipo)
                {
                    await _imghabitacionRepository.Delete(i.IdImgHabitaciones);
                }
                await _tiposHabitacionRepository.Delete(vm.eliminar.Value);
            }
            return RedirectToAction("TiposHabitaciones");


        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editartipo(TipoHabitacioneVM vm)
        {
            if (vm.editar.Value != 0)
            {

              var tipo=  await _tiposHabitacionRepository.GetbyId(vm.editar.Value);

                tipo.Nombre = vm.Nombre;
                tipo.Descripcion = vm.Descripcion;
                tipo.CantCamas = vm.CantCamas;
                tipo.MaxHuespedes = vm.MaxHuespedes;
                tipo.PrecioNoche = vm.PrecioNoche;
                await _tiposHabitacionRepository.Update(tipo);

            }
            return RedirectToAction("TiposHabitaciones");


        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editarhab(HabitacionVM vm)
        {
            if (vm.editar.Value != 0)
            {

                var tipo = await _HabitacionRepository.GetbyId(vm.editar.Value);

                tipo.IdEdificio = vm.IdEdificio;
                tipo.IdTipoHabitacion = vm.IdTipoHabitacion;
                tipo.NoHabitacion = vm.NoHabitacion.Value;
              
                await _HabitacionRepository.Update(tipo);

            }
            return RedirectToAction("Habitaciones");


        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BorrarHab(HabitacionVM vm)
        {
            if (vm.eliminar.Value != 0)
            {
                

                var imgs = await _HabitacionRepository.Delete(vm.eliminar.Value);

               
            }
            return RedirectToAction("Habitaciones");


        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BorrarEdi(EdificioVM vm)
        {
            if (vm.eliminar.Value != 0)
            {
                var list = await _HabitacionRepository.GetAll();
                var hab = list.Where(a => a.IdEdificio == vm.eliminar).ToList();
                if (hab.Count !=0)
                {
                    foreach (var item in hab)
                    {
                        var reservas = await _reservaRepository.GetAll();
                        var res = reservas.Where(a => a.IdHabitacion == item.IdHabitacion).ToList();

                     

                        await _HabitacionRepository.Delete(item.IdHabitacion);
                    }
                }
            }
                var imgs = await _EdificiosRepository.Delete(vm.eliminar.Value);


            
            return RedirectToAction("Edificios");


        }
        [HttpPost]
        public async Task<IActionResult> Añadiredificio(EdificioVM vm)
        {
            if (ModelState.IsValid)
            {
                var edi = new Edificio();
                edi.NumeroEdificio = vm.NumeroEdificio;
              await  _EdificiosRepository.Add(edi);
                return RedirectToAction("Edificios");
            }
            return View();

        }

SunHotel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SunHotel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SunHotel</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SunHotel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <partial name="_ValidationScriptsPartial" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SunHotel/Views/Shared/_LayoutEmail.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:v="urn:schemas-microsoft-com:vml">
<head>
    <!--[if gte mso 9]><xml><o:OfficeDocumentSettings><o:AllowPNG/><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml><![endif]-->
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
    <meta content="width=device-width" name="viewport" />
    <!--[if !mso]><!-->
    <meta content="IE=edge" http-equiv="X-UA-Compatible" />
    <!--<![endif]-->
    <title></title>
    <!--[if !mso]><!-->
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Bitter" rel="stylesheet" type="text/css" />
    <!--<![endif]-->
    <style type="text/css">
        body {
            margin: 0;
            padding: 0;
        }

        table,
        td,
        tr {
            vertical-align: top;
            border-collapse: collapse;
        }

        * {
            line-height: inherit;
        }

        a[x-apple-data-detectors=true] {
            color: inherit !important;
            text-decoration: none !important;
        }
    </style>
    <style id="media-query" type="text/css">
		@@media (max-width: 670px) {

			.block-grid,
			.col {
				min-width: 320px !important;
				max-width: 100% !important;
				display: block !important;
			}

			.block-grid {
				width: 100% !important;
			}

			.col {
				width: 100% !important;
			}

			.col_cont {
				margin: 0 auto;
			}

			img.fullwidth,
			img.fullwidthOnMobile {
				max-width: 100% !important;
			}

			.no-stack .col {
				min-width: 0 !important;
				display: table-cell !important;
			}

			.no-stack.two-up .col {
				width: 50% !important;
			}

			.no-stack .col.num2 {
				width: 16.6% !important;
			}

			.no-stack .col.num3 {
				width: 25% !important;
			}

			.no-stack .col.num4 {
				width: 33% !important;
			}

			.no-stack .col.num5 {
				width: 41.6% !important;
			}

			.no-stack .col.num6 {
				width: 50% !important;
			}

			.no-stack .col.num7 {
				width: 58.3% !important;
			}

			.no-stack .col.num8 {
				width: 66.6% !important;
			}

			.no-stack .col.num9 {
				width: 75% !important;
			}

			.no-stack .col.num10 {
				width: 83.3% !important;
			}

			.video-block {
				max-width: none !important;
			}

			.mobile_hide {
				min-height: 0px;
				max-height: 0px;
				max-width: 0px;
				display: none;
				overflow: hidden;
				font-size: 0px;
			}

			.desktop_hide {
				display: block !important;
				max-height: none !important;
			}
		}
    </style>
    <style id="icon-media-query" type="text/css">
		@@media (max-width: 670px) {
			.icons-inner {
				text-align: center;
			}

			.icons-inner td {
				margin: 0 auto;
			}
		}
    </style>
</head>
<body class="clean-body" style="margin: 0; padding: 0; -webkit-text-size-adjust: 100%; background-color: #FFFFFF;">
    <!--[if IE]><div class="ie-browser"><![endif]-->

    <div class="">
        <main role="main" class="">
            @RenderBody()
        </main>
    </div>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SunHotel/Views/Shared/_LayoutNortic.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SunHotel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="~/css/template.css">
    
    <style>
    .w-custom{
        width:75%;
    }
@@media (max-width: 600px) {
    .w-custom {
        width: 100%;
    }
  
}</style>

</head>
<body>
    <div class="bg1">
        <header>

            <div class="container-fluid  w-custom">
                <div class="w-50 mx-auto ">
                    <img src="~/img/escudo-RD.png" class="w-100 d-lg-none img-fluid" style="max-height: 40px !important;" alt="Escudo Dominicana" />
                </div>
                <div class="row">
                    <div class="col mr-3 text-black">

                        <a asp-controller="Home" asp-action="Index" target="_self" class="text-decoration-none" style="color:black;">
                            <!--[ESPECIFICAR LA RUTA AL INICIO DEL PORTAL]-->
                            <!--[SUSTITUIR ARCHIVO "logo.png" POR EL LOGO Y NOMBRE DE LA INSTITUCION]-->
                            <img src="~/img/logo.png"  height="145" title="Logo Sun Hotel" alt="Logo Sun Hotel">
                            
</a>
                    </div>
                    @*<div class="col ">
                        <a asp-controller="Home" asp-action="Index" class="text-decoration-none text-dark d-flex align-items-center"><h1 class="sunhotel margin-top-1">SunHotel</h1></a>
                    </div>*@
                    <div class="col d-none d-lg-block">
                        <div class="">
                            <div class="repDom w-100"></div>
                            <div class="pSearch">
                                <div class="search">
                                    <input name="search" type="text" id="mod-search-searchword">
                                    <input name="search" type="image" src="~/img/searchButton.gif">
                                </div>
                            </div>
                            <div class="navMenu">
                                <ul class="menu">
                                    <li><a asp-controller="Home" asp-action="Index">Inicio</a></li>
                                    <li><a href="#">Mapa de sitio</a></li>
                                    <li><a href="#">Contacto</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <nav class="navbar navbar-expand-lg navbar-light rounded shadow-sm " style="background-color: rgb(252, 252, 84);">
                    <a class="navbar-brand" href="#"><br /></a>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item active">
                                <a class="nav-link" asp-controller="Home" asp-action="Index">Inicio <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="ListHabitacion">HABITACIONES & SUITES</a>
                            </li>

                        </ul>
                        <form class="d-flex d-lg-none">
                            <input class="form-control mr-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                    </div>
                </nav>
            </div><!--end logo-->



        </header>
               <div class="container-fluid w-custom">

            <main role="main">
                @RenderBody()
            </main>

        </div><!--end contentMaster-->
    </div><!--end main-wrapp-->
   


    <footer>
        <div class="container-fluid p-3">

            <div class="d-none d-xl-block">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-sm">
                            <img src="~/img/footerLines.png" alt="Alternate Text" />
                        </div>
                        <div class="col-sm mr-1">
                            <img src="~/img/logosm.png" width="85" height="85" alt="Alternate Text" />

                        </div>
                        <div class="col-sm-1">
                            <img src="~/img/separator.gif" alt="Alternate Text" />
                        </div>
                        <div class="col-sm">
                            <img src="~/img/footerRd.gif" alt="Alternate Text" />
                        </div>
                        <div class="col-sm">
                            <img src="~/img/footerLines.png" alt="Alternate Text" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="w-100 container position-relative mt-3">
                <div class="m-0 mx-auto ">
                    <img class="d-xl-none mx-auto d-block img-fluid" src="~/img/logosm.png" alt="Alternate Text" />

                    <p class="text-center">
                        <a href="#" class="text-decoration-none text-dark">SunHotel Rep. Dominicana</a><!--[ESPECIFICAR LA RUTA AL INICIO DEL PORTAL]--><br>
                        Calle Khuala Lumpur, Punta Cana<br>
                        Tel: 809-999-9999<br />
                        <span>&copy; 2021 - Todos los Derechos Reservados</span>
                    </p><!--end info-->

                </div>
                    <div class="position-absolute " style="width:83px; height:100px; right:40px; bottom:15px " >
                        <img src="~/img/sello_nortic.png" alt="" class="d-none d-xl-block" title="" width="83" height="100" /><!--[RESERVADO PARA SELLO DE CERTIFICACION DE LA NORTIC A2]-->
                    </div>
            </div>
            <!--end infoFooter-->

        </div><!--end contentBoxMasterBox1-->
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <partial name="_ValidationScriptsPartial" />

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SunHotel/Views/Shared/_Layoutnew.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SunHotel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/simple-sidebar.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Zen+Dots&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/e9394416bd.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.1.5/css/fileinput.min.css" media="all" rel="stylesheet" type="text/css" />
    <!-- if using RTL (Right-To-Left) orientation, load the RTL CSS file after fileinput.css by uncommenting below -->
    <!-- link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.1.5/css/fileinput-rtl.min.css" media="all" rel="stylesheet" type="text/css" /-->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!-- piexif.min.js is needed for auto orienting image files OR when restoring exif data in resized images and when you
        wish to resize images before upload. This must be loaded before fileinput.min.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.1.5/js/plugins/piexif.min.js" type="text/javascript"></script>
    <!-- sortable.min.js is only needed if you wish to sort / rearrange files in initial preview.
        This must be loaded before fileinput.min.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.1.5/js/plugins/sortable.min.js" type="text/javascript"></script>
    <!-- popper.min.js below is needed if you use bootstrap 4.x. You can also use the bootstrap js
       3.3.x versions without popper.min.js. -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <!-- bootstrap.min.js below is needed if you wish to zoom and preview file content in a detail modal
        dialog. bootstrap 4.x is supported. You can also use the bootstrap js 3.3.x versions. -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- the main fileinput plugin file -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.1.5/js/fileinput.min.js"></script>
    <!-- optionally if you need a theme like font awesome theme you can include it as mentioned below -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.1.5/themes/fa/theme.js"></script>
    <!-- optionally if you need translation for your language then include  locale file as mentioned below -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.1.5/js/locales/(lang).js"></script>
</head>
<body>
    <div class="d-flex" id="wrapper">

        <!-- Sidebar -->
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="sidebar-heading h1">ADMIN</div>
            <div class="list-group list-group-flush">
                <a asp-controller="Admin" asp-action="Index" class="list-group-item list-group-item-action bg-light ">Dashboard</a>
                <a asp-controller="Admin" asp-action="TiposHabitaciones" class="list-group-item list-group-item-action bg-light">Tipo de Habitaciones</a>
                <a asp-controller="Admin" asp-action="Habitaciones" class="list-group-item list-group-item-action bg-light">Habitaciones</a>
                <a asp-controller="Admin" asp-action="Edificios" class="list-group-item list-group-item-action bg-light">Edificios</a>
                <a asp-controller="Admin" asp-action="Reserva" class="list-group-item list-group-item-action bg-light">Reportes</a>
            </div>
        </div>
        <!-- Page Content -->
        <div id="page-content-wrapper">

            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="#" style="font-family: 'Zen Dots', cursive;">
                    <img src="~/img/sunlogomin.png" width="30" height="30" class="d-inline-block align-top" alt="">

                    SunHotel
                </a>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                        <a asp-controller="Admin" asp-action="Logout" class="btn btn-danger float-right"><span><i class="fas fa-sign-out-alt"></i></span> Salir</a>

                    </ul>
                </div>
            </nav>

            <div class="container-fluid">
                <main role="main" class="pb-3">
                    <button class="btn btn-primary tog d-lg-none float-left  mt-2" id="menu-toggle"><i class="fas fa-caret-left"></i></button>
                    @RenderBody()
                </main>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>



    @*<div class="  d-flex justify-content-center">
            <div class="row">
                <div class="footer-centro">
                    <img src="~/img/2021-04-05 20_47_26-Window.png" width="100" height="100">
                    <a href="https://optic.gob.do/nortic/"> <img src="~/img/2021-03-16 22_19_16-Window.png" width="100" height="100"></a>
                    <a href="https://optic.gob.do/nortic/"> <img src="~/img/2021-03-16 22_11_09-Window.png" width="400" height="140" class="footer-derecha"></a>
                    <div class="footer-centro">
                        <ul>
                            <li class="underline">SunHotel Rep. Dominicana</li>
                            <li class="underline">Calle Khuala Lumpur, Punta Cana</li>
                            <li class="underline">Tel: 809-999-9999</li>
                            <li class="underline">hotelsun@turismo.com.do</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>*@
    <partial name="_ValidationScriptsPartial" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SunHotel/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SunHotel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>